package com.j256.simpleclassreader;

/**
 * Enumerated types of errors generated by reading in a class.
 * 
 * @author graywatson
 */
public enum ClassReaderErrorType {
	MAGIC_INVALID("magic number at the start of the class doesn't match 0xCAFEBABE, maybe not a class"),
	UNKNOWN_MAJOR_VERSION("unknown major version number"),
	CONSTANT_POOL_INFO_INVALID("invalid constant-pool class struction type"),
	CLASS_NAME_INDEX_INVALID("class name index does not point to valid location"),
	INTERFACE_NAME_INDEX_INVALID("interface name index does not point to valid location"),
	FIELD_NAME_INDEX_INVALID("field name index does not point to valid location"),
	FIELD_DATA_DESCRIPTOR_INDEX_INVALID("field data descriptor index does not point to valid location"),
	FIELD_DATA_DESCRIPTOR_INVALID("field data descriptor is invalid"),
	METHOD_NAME_INDEX_INVALID("method name index does not point to valid location"),
	METHOD_DESCRIPTOR_INDEX_INVALID("method descriptor index does not point to valid location"),
	ATTRIBUTE_NAME_INDEX_INVALID("attribute name index does not point to valid location"),
	ATTRIBUTE_NAME_UNKNOWN("attribute name is not known to the lubrary"),
	EXCEPTION_NAME_INDEX_INVALID("exception name index does not point to valid location"),
	ANNOTATION_NAME_INDEX_INVALID("annotation name index does not point to valid location"),
	ANNOTATION_TYPE_INDEX_INVALID("annotation data descriptor index does not point to a valid location"),
	ANNOTATION_TYPE_INVALID("annotation data descriptor is not valid"),
	ANNOTATION_ENUM_NAME_INDEX_INVALID("annotation enum value name index does not point to valid location"),
	ANNOTATION_ENUM_CONST_INDEX_INVALID("annotation enum value const index does not point to valid location"),
	ANNOTATION_VALUE_TAG_INVALID("annotation value has unknown tag"),
	CODE_CATCH_TYPE_INDEX_INVALID("code catch-type index does not point to valid location"),
	// end
	;

	private final String message;

	private ClassReaderErrorType(String message) {
		this.message = message;
	}

	public String getMessage() {
		return message;
	}
}
